### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by feknall** [AI-secure/DataLens#1]
Hi,

I am interested to test this project. However, the version of Tensorflow package is not provided. I have tried different versions and I got some different errors. Could you please let me know the version of Tensorflow? Additionally, maybe it is a good idea to add to the requirements.txt file as well.

**Comment by boxin-wbx** [comment]
Hi,

Thank you for your interest in our project. The version number of each package is already listed in [requirements.txt](https://github.com/AI-secure/DataLens/blob/9c02cfc9b775ae7a005772145563ca2251ab3761/requirements.txt#L3). For example, we are using `tensorflow-gpu==1.14.0`. 

Please let me know if you have further questions. Thank you!

**Comment by feknall** [comment]
Thank you for your quick response. I see the version of `tensorflow-gpu`, but I want to know the version of `tensorflow`, which is used in `dp_pca.py` and other files.
Additionally, let me know what is the exact version of python that you have used.

As I said before, I am trying to run this project, but I am getting some errors which I think are because of versions mismatch.

**Comment by boxin-wbx** [comment]
For tensorflow 1.x, you can install either `tensorflow-gpu` (for GPU) or `tensorflow` (for CPU only). DataLens has to be run on GPUs, so you need to install `tensorflow-gpu` and then you can successfully import tensorflow used in `dp_pca.py` and other files.

The project is tested on Python 3.6, but a higher version of Python should also work.
